#!/usr/bin/env bash

echo "Trying to find a user name for the cron job"
echo "ps: $(ps -o user= -p $$ | awk '{print $1}')"
echo "logname: $(logname)"
echo "whoami: $(whoami)"
echo "id: $(id -u -n)"
echo "USER: $USER"
echo "SUDO_USER: $SUDO_USER"

# Let's cycle through to find a non blank and non-root username
if [[ "$(ps -o user= -p $$ | awk '{print $1}')" != "root" && "$(ps -o user= -p $$ | awk '{print $1}')" != "" ]]; then
        MY_USER=$(ps -o user= -p $$ | awk '{print $1}')
elif [[ "$(logname)" != "root" && "$(logname)" != "" ]]; then
        MY_USER=$(logname)
elif [[ "$(whoami)" != "root" && "$(whoami)" != "" ]]; then
        MY_USER=$(whoami)
elif [[ "$(id -u -n)" != "root" && "$(id -u -n)" != "" ]]; then
        MY_USER=$(id -u -n)
elif [[ "$USER" != "root" && "$USER" != "" ]]; then
        MY_USER=$USER
elif [[ "$SUDO_USER" != "root" && "$SUDO_USER" != "" ]]; then
        MY_USER=$SUDO_USER
else
  echo "Cannot find the username! Skipping the crontab install"
fi

if [[ "$MY_USER" != "" ]]; then
  line="$((RANDOM%60)) 2 * * * /usr/bin/aws-rotate-iam-keys --profile default >/dev/null 2>&1 #rotate AWS keys daily"
  (crontab -u $MY_USER -l; echo "$line" ) | crontab -u $MY_USER -
fi
